mongodb/homebrew-brew

Aliases/mongodb-community@4.0
Formula/mongodb-community-shell.rb
Formula/mongodb-community.rb
Formula/mongodb-community@3.2.rb
Formula/mongodb-community@3.4.rb
Formula/mongodb-community@3.6.rb
LICENSE
README.md

This is what I hope to base our initial work on.

Add initial files to begin testing and experimenting with the new tap

---

Formula/mongodb-community.rb

This is for https://github.com/mongodb/homebrew-brew/issues/6.

Added the missing import

---

README.md

We have had a few issues [like this one](https://github.com/mongodb/homebrew-brew/issues/27) that are not actually related to the code in this repository and should go through our community resources. 
This template will add a disclaimer for users to read when opening their issue. Similar to the SCons project's issue template.

Add ISSUE_TEMPLATE.md

---

Formula/mongodb-community@4.2.rb

Hi Folks -- think this is the fix for SERVER-50058, but please double-check my work. Thanks.

fix class capitalization for MDB 4.2 formula

---

Formula/mongodb-community.rb
Formula/mongodb-community@3.6.rb
Formula/mongodb-community@4.0.rb
Formula/mongodb-community@4.2.rb

https://jira.mongodb.org/browse/SERVER-51092

SERVER-51092 update to latest MDB versions.

---

Formula/libmongocrypt.rb

Tested using my fork:
```
brew install kevinAlbs/brew/libmongocrypt
brew test kevinAlbs/brew/libmongocrypt
```

update libmongocrypt to 1.2.0

---

Formula/mongosh.rb

Reverts mongodb/homebrew-brew#91

Revert "mongosh 0.7.1"

---

Formula/mongodb-community.rb

Update mongodb-community from 4.4.4 to 4.4.5

Brew formula update for mongodb-community@4.4

---

Formula/libmongocrypt.rb

Tested with: `brew install kevinAlbs/brew/libmongocrypt`

update libmongocrypt to 1.3.0

---

Formula/libmongocrypt.rb

Tested with `brew install kevinAlbs/brew/libmongocrypt`

update libmongocrypt to 1.3.1

---

Aliases/mongodb-enterprise@6.0
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@4.2.rb
Formula/mongodb-enterprise@4.4.rb
Formula/mongodb-enterprise@5.0.rb

Added `mongodb-enterprise` formulae including license agreement warning.

Added Enterprise formulae

---

Formula/mongodb-community.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-mongocryptd.rb
README.md

Added formulae for M1 downloads for 6.0 community and crypt_shared.

Add M1 support

---

Aliases/mongodb-community-shell@5.0
Formula/mongodb-community-shell.rb
Formula/mongodb-community-shell@4.2.rb
Formula/mongodb-community-shell@4.4.rb
Formula/mongodb-community@4.2.rb
Formula/mongodb-community@4.4.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-enterprise@5.0.rb

updating to the latest versions
Drive by added some older test shell formulae

Update mongo versions

---

README.md

4.2 is not available as a formula anymore

Update README.md: Remove reference to 4.2

---

Formula/mongodb-database-tools.rb

Update mongodb-database-tools.rb for v100.7.4

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community-shell@4.4.rb
Formula/mongodb-community.rb
Formula/mongodb-community@4.4.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@4.4.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@4.4.rb
Formula/mongodb-mongocryptd@5.0.rb
Formula/mongodb-mongocryptd@6.0.rb

Updates homebrew links and hashes for new release versions using the mr tool from https://github.com/10gen/mongo-release-tools/pull/423

SERVER-80537 update formulas with new patch releases

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community-shell@4.4.rb
Formula/mongodb-community.rb
Formula/mongodb-community@4.4.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@4.4.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@4.4.rb
Formula/mongodb-mongocryptd@5.0.rb
Formula/mongodb-mongocryptd@6.0.rb

Update Homebrew Formulae to support new Major Patch Version 7.0.8

SERVER-88809 Update Homebrew Formulae for New Major Patch Release (7.0.8)

---

Formula/mongodb-community.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-mongocryptd.rb

https://jira.mongodb.org/browse/SERVER-90736

SERVER-90736 Update Homebrew Formulae for New Major Patch Release (7.0.11)

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-mongocryptd@5.0.rb

Update Homebrew Formulae to support new Major Patch Version 5.0.28

SERVER-92220 Update Homebrew Formulae for New Major Patch Release (5.0.28)

---

Formula/mongodb-community@6.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-mongocryptd@6.0.rb

Update Homebrew Formulae to support new Major Patch Version 6.0.17

SERVER-93563 Update Homebrew Formulae for New Major Patch Release (6.0.17)

---

Formula/mongodb-community.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-mongocryptd.rb

Update Homebrew Formulae for New Major Patch Release (7.0.14)

SERVER-93823 Update Homebrew Formulae for New Major Patch Release (7.0.14)

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@5.0.rb

This reverts commit 48fb01ac4de3ff7b9190d1ffffa170aad8764d11.

Revert "SERVER-94080 Fix 7.0.14 hashes and update 5.x to 5.0.29"

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-mongocryptd@5.0.rb

Update Homebrew Formulae for New Major Patch Release (5.0.29)

SERVER-94080 Update Homebrew Formulae for New Major Patch Release (5.0.29)

---

Formula/mongodb-community.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-mongocryptd.rb

Update Homebrew Formulae to support new Major Patch Version 8.0.1

SERVER-95529 Update Homebrew Formulae for New Major Patch Release (8.0.1)

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@5.0.rb
Formula/mongodb-mongocryptd@6.0.rb
Formula/mongodb-mongocryptd@7.0.rb

Upgrades to 5.0.30, 6.0.19, 7.0.16, and 8.0.4

SERVER-98324 Update Homebrew Formulae for New Major Patch Releases

---

Formula/mongodb-community@6.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-mongocryptd@6.0.rb

Update Homebrew Formulae for New Major Patch Release 6.0.20

SERVER-98797 Update Homebrew Formulae for New Major Patch Release (6.0.20)

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-mongocryptd@5.0.rb

SERVER-99781 Update Homebrew Formulae for New Major Patch Release (5.0.31)

SERVER-99781 Update Homebrew Formulae for New Major Patch Release (5.0.31)

---

Formula/mongodb-community.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@7.0.rb

Update Homebrew Formulae for New Major Patch Release (8.0.5/7.0.17)

SERVER-101039 Update Homebrew Formulae for New Major Patch Release (8.0.5/7.0.17)

---

Formula/mongodb-community.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@6.0.rb

SERVER-102496 Update Homebrew Formulae for New Major Patch Release

---

Formula/mongodb-community.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@6.0.rb
Formula/mongodb-mongocryptd@7.0.rb

Update Homebrew Formulae for New Major Patch Release (6.0.22/7.0.19/8.0.8)

SERVER-103574 Update Homebrew Formulae for New Major Patch Release (6.0.22/7.0.19/8.0.8)

---

Formula/mongodb-community.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@6.0.rb
Formula/mongodb-mongocryptd@7.0.rb

Update Homebrew Formulae for New Major Patch Releases (6.0.23, 7.0.20, 8.0.9)

SERVER-104439 Update Homebrew Formulae for New Major Patch Releases (6.0.23, 7.0.20, 8.0.9)

---

Formula/mongodb-community.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@6.0.rb
Formula/mongodb-mongocryptd@7.0.rb

Update Homebrew Formulae for New Major Patch Release (6.0.24/7.0.21/8.0.10)

SERVER-105642 Update Homebrew Formulae for New Major Patch Release (6.0.24/7.0.21/8.0.10)

---

Formula/mongodb-community.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-database-tools.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@6.0.rb
Formula/mongodb-mongocryptd@7.0.rb

Update Homebrew Formulae for New Major Patch Release (6.0.25/7.0.22/8.0.12)

SERVER-107750 Update Homebrew Formulae for New Major Patch Release (6.0.25/7.0.22/8.0.12)

---

Formula/mongodb-community.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-csfle.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@6.0.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@6.0.rb
Formula/mongodb-mongocryptd@7.0.rb

Update Homebrew Formulae for New Major Patch Release (8.0.13/7.0.23/6.0.26)

SERVER-109334 Update Homebrew Formulae for New Major Patch Release (8.0.13/7.0.23/6.0.26)

---

Formula/mongodb-community.rb
Formula/mongodb-community@7.0.rb
Formula/mongodb-community@8.0.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@7.0.rb
Formula/mongodb-enterprise@8.0.rb
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@7.0.rb
Formula/mongodb-mongocryptd@8.0.rb

Update Homebrew Formulae for New Major Patch Release (8.2.1, 8.0.15, 7.0.25)

SERVER-111766 Update Homebrew Formulae for New Major Patch Release (8.2.1, 8.0.15, 7.0.25)
