Formula/mongodb-community.rb

This utilizes the "current" release stream. We'll need to figure out how to accomplish this for the mongodb-community-shell Formula separately as that build artifact is not in the current release stream today.

Automatically install the latest GA release

---

Formula/mongodb-community-shell.rb

While the package is not available in the release stream, we're able to utilize the stream in order to determine the latest GA version and then construct the download artifact URLs from there.

Automatically install the latest GA Shell

---

Formula/mongodb-community.rb
Formula/mongodb-community@3.2.rb
Formula/mongodb-community@3.4.rb
Formula/mongodb-community@3.6.rb

Then when we do a major upgrade we can copy one of the existing ones and simply change the version regex.

Automatically grab the latest patch releases for 3.x

---

Formula/mongodb-community-shell.rb
Formula/mongodb-community.rb
Formula/mongodb-community@3.2.rb
Formula/mongodb-community@3.4.rb
Formula/mongodb-community@3.6.rb

`downloads.mongodb.org/current.json` should be accessed using HTTPS instead of HTTP for obvious security reasons.

Use https instead of http

---

Formula/mongodb-community.rb

```
$ shasum -a 256 mongodb-macos-x86_64-4.2.0.tgz
6aa2e0c348e8abeec7931dced1f85d4bb161ef209c6af317fe530ea11bbac8f0
```

Fixed mismatch SHA256 checksum

---

Formula/mongosh.rb

Does an npm install with a Node dependency to get mongosh on MacOS via `mongosh`

Adding Homebrew Formula for mongosh

---

Formula/mongosh.rb

With https://jira.mongodb.org/browse/MONGOSH-243 we exit with an error when the node version is not the one we expect (`^12.4.0` for `mongosh v0.0.6`). 
Because homebrew by default installs latest stable (14) when `node` is used as a dependency, mongosh installed with this formula refuses to start on systems where node isn't already installed and the homebrew one is used as the default.
With this PR we pin node to `v12`.

Pin node version to 12

---

Formula/mongosh.rb

Fixed the install/link of the formula:
- Install uses node12's npm
- Install creates a wrapper script that puts Homebrew's node12 in PATH for mongosh to run.

Always runs mongosh with node 12

---

Formula/mongodb-community.rb

The server tools are not distributed with MongoDB v4.4 and higher
anymore. From now on, there will be a recommended dependency on the
mongodb-database-tools package so that users who expected the tools to be
installed by default will get them, since that is the likely use case
for most users of this Homebrew tap. Users who do not want the tools
installed can now opt out of them.

SERVER-45930 Add new recommended dependency on mongodb-database-tools

---

Formula/libmongocrypt.rb

This is the library used by drivers to support Client-Side Field Level Encryption.
The PR to merge in homebrew-core was closed (https://github.com/Homebrew/homebrew-core/pull/63229) since it is currently not notable enough (based on stars / watchers / and forks). The maintainers suggested hosting this on a tap.

SERVER-51790 add libmongocrypt formula

---

README.md

• Small typo fix for 4.4 formula install step
• DB Tools links now link to DB Tools docs repo (not manual > reference > package contents)
• Updating name from 'command-line tools' to 'Database Tools' across the board.
• Added DB Tools-only install similar to shell-only install.
@rychipman for OKing DB Tools naming changes / link updates / install-only-DBTools step

Typo fix and update for Database Tools

---

Formula/libmongocrypt.rb

I tested by pushing this to my fork first and running `brew audit --strict --online` and installing via `brew install kevinAlbs/brew/libmongocrypt --head`.

add head URL to libmongocrypt

---

Formula/mongodb-community.rb
Formula/mongodb-community@3.6.rb
Formula/mongodb-community@4.0.rb
Formula/mongodb-community@4.2.rb

Minor versions were outdated. Updated SHA256 hashes using this info: https://docs.mongodb.com/manual/tutorial/verify-mongodb-packages/#use-sha-256

Upgrade formula versions for mongodb-community

---

Aliases/mongodb-mongocryptd@4.4
Formula/mongodb-mongocryptd.rb
Formula/mongodb-mongocryptd@4.2.rb

This PR adds 2 new formulas to allow easy installation of `mongocryptd` for users that require Client Side Field Level Encryption with `mongosh`.
The following formulas are added:
* `mongodb-mongocryptd`: which references the latest stable version `4.4.6`
* `mongodb-mongocryptd@4.2`: for server version `4.2.14`
The formula will show _caveats_ to point out the licensing:

chore: add new formula for mongocryptd MONGOSH-800

---

Formula/mongodb-community.rb

This adds the `mongosh` formula as a `recommended` formula to the `mongodb-community` formula.
See https://jira.mongodb.org/browse/MONGOSH-128.

add mongosh as dependency to mongodb-community MONGOSH-128

---

Formula/mongodb-community.rb

The [default mac hosts file](https://gist.github.com/andretw/e3946bd9c9b4571702e5) includes an IPv6 alias for localhost. The default behavior of the [nodejs mongodb client](https://docs.mongodb.com/drivers/node/current/fundamentals/connection/#connection-options) is to attempt a connection with IPv6 before falling back to IPv4. I was getting connection errors until I went and added `ipv6: true` to the mongod configuration file and then it connected just fine.
My impression is that given the default in the hostfile, it would be better for the homebrew installation to assume IPv6 by default.
* Add `ipv6: true` to the default configuration file for installation

Add ipv6: true to the default configuration file

---

README.md

The $ will cause issues when using the copy code button introduced in github recently.

Remove $ prefix from shell commands

---

Formula/libmongocrypt.rb

Tested with: `brew install kevinAlbs/brew/libmongocrypt` and `brew install kevinAlbs/brew/libmongocrypt --HEAD`

update libmongocrypt stable to 1.4.0, and HEAD to 1.5.0-rc0

---

Formula/mongodb-csfle.rb

In 544b5683217285ec, we added mongocryptd so that users could install
it alongside mongosh through homebrew. mongosh is switching over to
using the CSFLE shared library that is expected to replace mongocryptd
in the long run. Consequently, we add it here as well as part of
our migration project.

Add new formula for CSFLE shared library MONGOSH-1119

---

Formula/libmongocrypt.rb

```
$ brew install kevinAlbs/brew/libmongocrypt
...
$ pkg-config --modversion libmongocrypt
1.5.0
```
```
$ brew install kevinAlbs/brew/libmongocrypt --HEAD
...
$ pkg-config --modversion libmongocrypt
1.6.0-pre
```

update libmongocrypt to 1.5.0

---

Formula/libmongocrypt.rb

This release addresses a severe and urgent bug fix: MONGOCRYPT-464.
```
$ brew install kevinAlbs/brew/libmongocrypt
...
$ pkg-config --modversion libmongocrypt
1.5.2
```

bump libmongocrypt to 1.5.2

---

Formula/libmongocrypt.rb

update libmongocrypt formula for 1.6.0

---

Formula/libmongocrypt.rb

update libmongocrypt to 1.6.2

---

Formula/libmongocrypt.rb

Tested from a fork with the following
```
...
1.7.0
```

update libmongocrypt to 1.7.0

---

Formula/libmongocrypt.rb

update libmongocrypt to 1.7.1

---

Formula/libmongocrypt.rb

update libmongocrypt to 1.7.2

---

Formula/libmongocrypt.rb

update to libmongocrypt 1.7.4

---

Formula/libmongocrypt.rb

update to libmongocrypt 1.8.0

---

Formula/libmongocrypt.rb

update to libmongocrypt 1.8.1

---

Formula/libmongocrypt.rb

update to libmongocrypt 1.8.2

---

Formula/mongodb-community.rb
Formula/mongodb-community@4.4.rb
Formula/mongodb-community@5.0.rb
Formula/mongodb-community@6.0.rb
Formula/mongodb-enterprise.rb
Formula/mongodb-enterprise@4.4.rb
Formula/mongodb-enterprise@5.0.rb
Formula/mongodb-enterprise@6.0.rb

Homebrew seems to have changed the way it starts up services, now we need to use the service stanza: https://docs.brew.sh/Formula-Cookbook#service-files
This was reported in homebrew as well:
https://github.com/Homebrew/homebrew-services/issues/607
Tested with these commands:
```
brew untap mongodb/homebrew-brew
brew tap dmoody256/homebrew-brew
brew install mongodb-community
brew services restart mongodb/brew/mongodb-community
ps aux | grep mongod
```

Update service startup to work with homebrew 4.2

---

Formula/libmongocrypt.rb

- Address build error observed in [MONGOCRYPT-667](https://jira.mongodb.org/browse/MONGOCRYPT-667)
- Update libmongocrypt formula to 1.9.0
Homebrew includes `FETCHCONTENT_FULLY_DISCONNECTED=ON` as part of https://github.com/Homebrew/brew/pull/17075. This resulted in breaking the build process due to skipping necessary build downloads.
```
[...]
1.9.0
```

MONGOCRYPT-667 update to libmongocrypt 1.9.0

---

Formula/libmongocrypt.rb

Update libmongocrypt formula to 1.10.1
```
[...]
1.10.1
```

MONGOCRYPT-673 update to libmongocrypt 1.10.1

---

Formula/libmongocrypt.rb

Update libmongocrypt formula to 1.11.0
```
[...]
1.11.0
```

update to libmongocrypt 1.11.0

---

Formula/libmongocrypt.rb

Update libmongocrypt formula to 1.12.0
```
[...]
1.12.0
```

MONGOCRYPT-732 update to libmongocrypt 1.12.0

---

Formula/libmongocrypt.rb

Update libmongocrypt formula to 1.13.1
```
[...]
1.13.1
```

update libmongocrypt to 1.13.1

---

Formula/libmongocrypt.rb

Update libmongocrypt formula to 1.13.2
Needed to fix Homebrew install. See MONGOCRYPT-797.
Tested with following:
```
[...]
1.13.2
```

bump libmongocrypt to 1.13.2

---

Formula/mongodb-database-tools.rb

Verified that this is the expected sha, made a mistake when generating this originally

correct the arm64 sha for mongodb-database-tools

---

Formula/libmongocrypt.rb

Update libmongocrypt formula to 1.14.1
```
[...]
1.14.1
```

update libmongocrypt for 1.14.1
